# Generated by Django 3.1.2 on 2020-10-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('netid', models.CharField(max_length=45)),
                ('uin', models.IntegerField(default=0)),
            ],
        ),
    ]
